[project]
name = "autocleaner"
version = "0.1.0"
description = "Utilities for LHC turn-by-turn denoising experiments."
requires-python = ">=3.10"
dependencies = [
    "matplotlib",
    "omc3",
    "pytorch-lightning",
    "tensorboard",
    "torch==2.6.0 ; sys_platform == 'darwin'",
    "torch==2.6.0 ; sys_platform == 'linux'",
    "xtrack-tools @ git+https://github.com/jgray-19/xtrack_tools.git",
    "lhcng @ git+https://github.com/jgray-19/lhcng.git@a86a880b4dad12b6f14b133687c45b40ced3dba4"
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[tool.uv]
package = false
